apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Mersock/eks-auto-scaling-and-strategies-ops.git
      targetRevision: main
      path: gitops/charts/karpenter
      helm:
        releaseName: karpenter
        valueFiles:
          - ../../platform/karpenter/values.yaml
    - repoURL: https://github.com/Mersock/eks-auto-scaling-and-strategies-ops.git
      targetRevision: main
      path: gitops/platform/karpenter
      directory:
        exclude: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
