replicas: 1

serviceAccount:
  name: karpenter-sa

controller:
  env:
    - name: AWS_REGION
      value: ap-southeast-1

settings:
  clusterName: eks-ops-cluster
  interruptionQueue: eks-ops-cluster-karpenter

serviceMonitor:
  enabled: true
  additionalLabels:
    release: monitoring
